# Generated by Django 4.0.5 on 2022-06-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0004_entregable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name_plural': 'Profesores'},
        ),
    ]
